### ISSUE TITLE
http://gelisam.com/ludum-dare-34-postjam/ is down 

### ISSUE THREAD

**Issue by schell** [gelisam/ludum-dare-34#1]
The hosted game is down!

**Comment by gelisam** [comment]
Hmm, you're right! I moved gelisam.com to a new hosting provider recently, I probably forgot to move the game along with it. Thanks for reporting it!

**Comment by schell** [comment]
:+1: Can't wait to play :)

**Comment by gelisam** [comment]
Fixed!

**Comment by schell** [comment]
Cool! Nice animation.
